<?php

namespace Cooperative\CooperativeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItineraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItineraireRepository extends EntityRepository
{

	public function findByDepartDestination($depart, $destination)
	{
		$query = $this->_em->createQuery("SELECT a FROM CooperativeBundle:Itineraire a WHERE a.depart = ".$depart." and a.destination = ".$destination);
		return $query->getResult();
	}

	public function getIfExistItineraire($depart, $destination)
	{
		$id = 0;
		$query = $this->_em->createQuery("SELECT a FROM CooperativeBundle:Itineraire a WHERE a.depart = '".$depart."' and a.destination = ".$destination);
		$entites = $query->getResult();

		foreach ($entites as $e)
		{
			$id = $e->getId();
			break;
		}
		return $id;
	}

	public function itineraireGetLocalisation($localisation)
	{
		$qb = $this->createQueryBuilder('a')
					->leftJoin('a.'.$localisation, 'l')
					->addSelect('l');
					return $qb->getQuery()->getResult();

	}

	public function findAllByCooperative($cooperative)
	{
		$query = $this->_em->createQuery("SELECT a FROM CooperativeBundle:Itineraire a  JOIN CooperativeBundle:ItineraireCoop c where a.id = c.itineraire and c.cooperative = ".$cooperative);
		return $query->getResult();
	}

	public function findJoinItineraire()
	{
		$query = $this->_em->createQuery("SELECT a FROM CooperativeBundle:Itineraire a  JOIN CooperativeBundle:ItineraireCoop c where a.id = c.itineraire GROUP BY a.id");
		return $query->getResult();
	}

}
