<?php

namespace Cooperative\CooperativeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends EntityRepository
{
	public function getAllTrajetByItineraire($cooperative)
	{
		$query = $this->_em->createQuery('SELECT a FROM CooperativeBundle:Trajet a JOIN CooperativeBundle:ItineraireCoop c where a.itinerairecoop = c.id JOIN  CooperativeBundle:Itineraire i where c.itineraire = i.id and c.cooperative = '.$cooperative);
		return $entites = $query->getResult();
	}

	public function getTrajetByUser($depart, $destination, $date, $horaire, $place, $nbrPlace, $cooperative)
	{
		$request = "SELECT a FROM CooperativeBundle:Trajet a JOIN CooperativeBundle:ItineraireCoop c where a.itinerairecoop = c.id JOIN  CooperativeBundle:Itineraire i where c.itineraire = i.id and i.depart = ".$depart." and i.destination = ".$destination." JOIN BtaxBundle:Cooperative coop where c.cooperative = coop.id JOIN CooperativeBundle:Place p where p.id = c.place and a.date = '".$date."' and a.placeRestante >= ".$nbrPlace;

        if($cooperative != null)
        {
            $request = $request." and coop.nom like '".$cooperative."'";
        }


        if($horaire != null && $horaire != 1)
        {
            if($horaire == 3)
            {
                $request = $request." and a.heure > '12:00:00'";
            }
            else
            {
                $request = $request." and a.heure <= '12:00:00'";
            }
        }

        if($place != null || $place != 0)
        {
            $request = $request." and p.typePlace = '".$place."'";
        }


        $query = $this->_em->createQuery($request);
		return $entites = $query->getResult();
	}

    public function getTrajetByAdmin($date, $depart, $destination, $cooperative)
    {
        $request = "SELECT a FROM CooperativeBundle:Trajet a JOIN CooperativeBundle:ItineraireCoop c where a.itinerairecoop = c.id JOIN CooperativeBundle:Itineraire i where c.itineraire = i.id JOIN BtaxBundle:Cooperative coop where c.cooperative = coop.id and a.date = '".$date."'";

        if($depart != 0)
        {
            $request = $request." and i.depart = ".$depart;
        }

        if($destination != 0)
        {
            $request = $request." and i.destination = ".$destination;
        }

        if($cooperative != 0)
        {
            $request = $request." and coop.id = '".$cooperative."'";
        }

        $query = $this->_em->createQuery($request);
        return $entites = $query->getResult();
    }

    public function findPrix($id)
    {
        $query = $this->_em->createQuery('SELECT a FROM CooperativeBundle:Trajet a JOIN CooperativeBundle:ItineraireCoop c where a.itinerairecoop = c.id and a.id = '.$id);
        return $entites = $query->getResult();
    }

}
