<?php

namespace Book\BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationUserRepository extends EntityRepository
{
}
