<?php

namespace Book\BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function getReservationByMail($mail)
	{
		$query = $this->_em->createQuery("SELECT a FROM BookBundle:Reservation a INNER JOIN BookBundle:ReservationUser ru WHERE a.id = ru.reservation INNER JOIN UtilisateursBundle:Utilisateurs u WHERE ru.utilisateurs = u.id and u.email = '".$mail."'");
		return $entities = $query->getResult();
	}

	public function getReservationByDate($d_debut, $d_fin, $depart, $destination)
	{
		$query = "SELECT a FROM BookBundle:Reservation a ";
		if($depart != 0 || $destination !=0 )
		{
			$query = $query.' INNER JOIN CooperativeBundle:Trajet t WHERE t.id = a.trajet INNER JOIN CooperativeBundle:ItineraireCoop ic WHERE ic.id = t.itinerairecoop INNER JOIN CooperativeBundle:Itineraire i WHERE i.id = ic.itineraire ';
		}

		if($depart != 0)
		{
			$query = $query.' AND i.depart ='.$depart;
		}

		if($destination != 0)
		{
			$query = $query.' AND i.destination ='.$destination;
		}

		if($depart != 0 || $destination !=0 )
		{
			$query = $query.' AND';
		}
		else
		{
			$query = $query.' WHERE';
		}

		$query = $query." a.dateHeure between '".$d_debut."' and '".$d_fin."'";
		$query = $this->_em->createQuery($query);
		return $entities = $query->getResult();
	}
}
