security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER :       ROLE_USER
        ROLE_USER_COOP:   ROLE_USER_COOP
        ROLE_ADMIN_COOP:   ROLE_ADMIN_COOP
        ROLE_USER_BTAX:   ROLE_USER_BTAX
        ROLE_ADMIN_BTAX:   ROLE_ADMIN_BTAX

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /index
            logout:       true
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/sadmin/btax, role: ROLE_ADMIN_BTAX }
        - { path: ^/sadmin/cooperative, role: ROLE_ADMIN_COOP }
        - { path: ^/book/, role: ROLE_USER }