<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * luserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LuserRepository extends EntityRepository
{
}
