<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * luserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository
{
	public function findUserByUsername($user)
	{
		$query = $this->_em->createQuery('SELECT a FROM UtilisateursBundle:Utilisateurs a WHERE a.username = \''.$user.'\'');
		$resultats = $query->getResult();
		return $resultats;
	}

	public function findUserBtax()
	{
		$query = $this->_em->createQuery('SELECT a FROM UtilisateursBundle:Utilisateurs a WHERE a.roles LIKE \'%ROLE_USER_BTAX%\'');
		$resultats = $query->getResult();
		return $resultats;
	}

	public function findAllUser($choice, $user)
	{
		$query = $this->_em->createQuery('SELECT a FROM UtilisateursBundle:Utilisateurs a WHERE a.'.$choice.' LIKE \''.$user.'\'');
		$resultats = $query->getResult();
		return $resultats;
	}

	public function findUsersCooperative($cooperative)
	{
		$query = $this->_em->createQuery('SELECT a FROM UtilisateursBundle:Utilisateurs a JOIN UtilisateursBundle:Luser l WHERE a.id = l.user and l.owner = '.$cooperative.' and a.roles LIKE \'%ROLE_USER%\'');
		$resultats = $query->getResult();
		return $resultats;
	}

	public function findCooperativeLogo($user)
	{
		$query = $this->_em->createQuery('SELECT a FROM UtilisateursBundle:Utilisateurs a INNER JOIN BtaxBundle:Cooperative c WHERE a.id = c.login and a.id = \''.$user.'\'');
		$resultats = $query->getResult();
		return $resultats;
	}

}

