<?php

namespace Proxies\__CG__\Cooperative\CooperativeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \Cooperative\CooperativeBundle\Entity\Voiture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'immatriculation', 'nomProprietaire', 'nIF', 'nbrPlace', 'place', 'cooperative');
        }

        return array('__isInitialized__', 'id', 'immatriculation', 'nomProprietaire', 'nIF', 'nbrPlace', 'place', 'cooperative');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Voiture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setImmatriculation($immatriculation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImmatriculation', array($immatriculation));

        return parent::setImmatriculation($immatriculation);
    }

    /**
     * {@inheritDoc}
     */
    public function getImmatriculation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImmatriculation', array());

        return parent::getImmatriculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProprietaire($nomProprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProprietaire', array($nomProprietaire));

        return parent::setNomProprietaire($nomProprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProprietaire', array());

        return parent::getNomProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNIF($nIF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNIF', array($nIF));

        return parent::setNIF($nIF);
    }

    /**
     * {@inheritDoc}
     */
    public function getNIF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNIF', array());

        return parent::getNIF();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace($place)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', array($place));

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', array());

        return parent::getPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setCooperative(\Btax\BtaxBundle\Entity\Cooperative $cooperative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCooperative', array($cooperative));

        return parent::setCooperative($cooperative);
    }

    /**
     * {@inheritDoc}
     */
    public function getCooperative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCooperative', array());

        return parent::getCooperative();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrPlace($nbrPlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrPlace', array($nbrPlace));

        return parent::setNbrPlace($nbrPlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrPlace', array());

        return parent::getNbrPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
