<?php

namespace Btax\BtaxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository
{
	public function findAvisCooperativeUtilisateur($cooperative, $utilisateur)
	{
		$query = $this->_em->createQuery("SELECT a FROM BtaxBundle:Avis a WHERE a.cooperative = '".$cooperative."' and a.utilisateur = '".$utilisateur."'");
		$entities = $query->getResult();
		$e = $entities;
		
		foreach ($entities as $entity){
			$e = $entity;
			break;
		}
		return $e;
	}
}
